### ISSUE TITLE
ImportError: cannot import name 'COLUMN_DATA_TYPES'

### ISSUE THREAD

**Issue by iamharikrishnank** [mindsdb/lightwood#699] opened 2021-10-28 14:46 UTC
When I am trying to import column data from light wood following error occurs:
<ipython-input-8-40641743145d> in <module>
----> 1 from lightwood import COLUMN_DATA_TYPES, BUILTIN_MIXERS, BUILTIN_ENCODERS
      2 config = {
      3 
      4         ## REQUIRED:
      5         'input_features': [

ImportError: cannot import name 'COLUMN_DATA_TYPES'

**Comment by paxcema** [comment] 2021-10-29 19:12
Okay, that seems like the old tutorial. Can you try following the new instructions [here](https://github.com/mindsdb/lightwood/blob/staging/README.md)? It should work okay.

**Comment by paxcema** [comment] 2021-11-01 04:04
@iamharikrishnank Did you manage to get it working?

**Comment by iamharikrishnank** [comment] 2021-11-01 05:21
@paxcema I have occured  an error while doing it.actually I want to change data type to categorical:
~/mindsdb/env_python/lib/python3.6/site-packages/lightwood/api/json_ai.py in generate_json_ai(type_information, statistical_analysis, problem_definition)
    341     else:
    342         raise Exception(
--> 343             f"Please specify a custom accuracy function for output type {output_dtype}"
    344         )
    345 

Exception: Please specify a custom accuracy function for output type short_text

**Comment by paxcema** [comment] 2021-11-01 15:04
Hi @iamharikrishnank,

It seems you are trying to predict a short text column? Out of curiosity, what accuracy function would you say is appropriate for this dataset?

In the meantime, you can check [this](https://github.com/mindsdb/lightwood/issues/713) issue to track progress regarding easier custom accuracy function support.

**Comment by paxcema** [comment] 2021-11-08 15:53
Will close this, not a bug in the current release. Please refer to the above linked issue for status on custom accuracy functions.

**Closed by paxcema** 2021-11-08 15:53 UTC
